name: Update README with Latest Messages

on:
  issues:
    types: [opened, edited]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get the 5 most recent issue messages
      - name: Get the 5 most recent issue messages
        id: get_messages
        run: |
          # Fetch the last 5 issues labeled as 'message'
          messages=$(curl -s -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
            "https://api.github.com/repos/${{github.repository}}/issues?labels=message&sort=created&direction=desc&per_page=5" | \
            jq -r '.[].body')

          # Format the messages with a limit of 20 characters (if exceeded, append '...')
          formatted_messages=$(echo "$messages" | awk '{if(length($0) > 20) {print substr($0, 1, 20) "..."} else {print $0}}')

          # Store formatted messages in an environment variable for later use
          echo "MESSAGES=$formatted_messages" >> $GITHUB_ENV

      # Update README with the latest 5 messages
      - name: Update README with 5 latest messages
        run: |
          echo "Updating README with the 5 most recent messages..."
          echo "### Latest Messages from Supporters:" >> README.md
          echo "$MESSAGES" >> README.md

      # Commit and push the changes
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with new supporter messages"
          git push
